{{- if .Values.ping.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}-ping
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.ping.service }}
  {{- range $key, $value := .Values.ping.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    app: {{ template "traefik.name" . }}
    release: {{ .Release.Name }}
  ports:
  - port: 80
    {{- if (empty .Values.ping.port) }}
    targetPort: 82
    {{- else }}
    targetPort: {{ .Values.ping.port }}
    {{- end }}
    {{- if (not (empty .Values.ping.nodePort))}}
    nodePort: {{ .Values.ping.nodePort }}
    {{- end }}
{{- end }}
