{{- if .Values.ping.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "traefik.fullname" . }}-ping
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.ping.ingress }}
  {{- range $key, $value := .Values.ping.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
  {{- if .Values.ping.ingress }}
  {{- range $key, $value := .Values.ping.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ping.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "traefik.fullname" . }}-ping
          servicePort: 80
{{- end }}
